credentials:
  - id: "1"
    email: "mail1@gmail.com"
    app_password: "7b6ef775675E11c"
    smtp_host: "smtp.gmail.com"
    smtp_port: "587"
    subject: "Bug Bounty Report: Unauthenticated Remote Code Execution via CVE-2025-55182"

  - id: "2"
    email: "mail2@gmail.com"
    app_password: "f44134daf6830cc"
    smtp_host: "smtp.gmail.com"
    smtp_port: "587"
    subject: "Bug Bounty Report: Unauthenticated Remote Code Execution via CVE-2025-55182"

  - id: "3"
    email: "test1@org1.com"
    app_password: "$@#$SDFSDFSDFAFAFDFFAD"
    smtp_host: "email-smtp.eu-north-1.amazonaws.com"
    smtp_port: "587"
    smtp_username: "ASDFDSFFDFD"
    subject: "Bug Bounty Report: Unauthenticated Remote Code Execution via CVE-2025-55182"

  - id: "4"
    email: "test2@org2.com"
    app_password: "4234@#SFSFSDFF"
    smtp_host: "email-smtp.eu-north-1.amazonaws.com"
    smtp_port: "587"
    smtp_username: "SFSDSDFdsf"
    subject: "Bug Bounty Report: Unauthenticated Remote Code Execution via CVE-2025-55182"